# Generated by Django 4.2.7 on 2023-12-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_auctionlisting_discription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_url",
            field=models.URLField(max_length=255),
        ),
    ]
