# Generated by Django 4.2.7 on 2023-12-20 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auctionlisting_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="starting_bid",
            field=models.IntegerField(),
        ),
    ]
