# Generated by Django 4.2.7 on 2023-12-29 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bid_bid_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
