# Generated by Django 4.2.7 on 2024-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_comment_comment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
